export const data = {
  generalInfo: {
    categories: {
      firstCategory: [
        { value: 'option1', label: 'Option 1' },
        { value: 'option2', label: 'Option 2' },
        { value: 'option3', label: 'Option 3' },
      ],
      secondCategory: [
        { value: 'option4', label: 'Option 4' },
        { value: 'option5', label: 'Option 5' },
        { value: 'option6', label: 'Option 6' },
      ],
    },
    styleFilter: [
      { value: '선택안함' },
      { value: '심플베이직' },
      { value: '러블리' },
      { value: '페미닌' },
      { value: '캐주얼' },
      { value: '섹시글램' },
    ],
    ageFilter: [
      { value: '10대', label: '10대' },
      { value: '20대', label: '20대' },
      { value: '30대', label: '30대' },
      { value: '40대', label: '40대' },
      { value: '50대', label: '50대' },
    ],
    colorFilter: [
      { valueKor: '빨강', valueEng: 'Red' },
      { valueKor: '주황', valueEng: 'Orange' },
      { valueKor: '노랑', valueEng: 'Yellow' },
      { valueKor: '베이지', valueEng: 'Beige' },
      { valueKor: '갈색', valueEng: 'Brown' },
      { valueKor: '초록', valueEng: 'Green' },
      { valueKor: '민트', valueEng: 'Mint' },
      { valueKor: '하늘', valueEng: 'Skyblue' },
      { valueKor: '파랑', valueEng: 'Blue' },
      { valueKor: '남색', valueEng: 'Navy' },
      { valueKor: '보라', valueEng: 'Violet' },
      { valueKor: '분홍', valueEng: 'Pink' },
      { valueKor: '흰색', valueEng: 'White' },
      { valueKor: '회색', valueEng: 'Gray' },
      { valueKor: '검정', valueEng: 'Black' },
      { valueKor: '골드', valueEng: 'Gold' },
      { valueKor: '로즈골드', valueEng: 'Rosegold' },
      { valueKor: '실버', valueEng: 'Silver' },
    ],
  },
};
