import React from 'react';
import HomeIcon from '@material-ui/icons/Home';
import PersonIcon from '@material-ui/icons/Person';
import AddShoppingCartIcon from '@material-ui/icons/AddShoppingCart';
import ShoppingCartIcon from '@material-ui/icons/ShoppingCart';
import AssessmentIcon from '@material-ui/icons/Assessment';
import LocalMallIcon from '@material-ui/icons/LocalMall';
import ShareIcon from '@material-ui/icons/Share';
import EmojiEmotionsIcon from '@material-ui/icons/EmojiEmotions';
import IsoIcon from '@material-ui/icons/Iso';
import VisibilityIcon from '@material-ui/icons/Visibility';
import CardGiftcardIcon from '@material-ui/icons/CardGiftcard';
import NotificationsActiveIcon from '@material-ui/icons/NotificationsActive';
import ChatIcon from '@material-ui/icons/Chat';
import MoreHorizIcon from '@material-ui/icons/MoreHoriz';
import SettingsIcon from '@material-ui/icons/Settings';

const data = {
  listData: {
    공지사항: [ChatIcon, <ChatIcon />],
    통계: [AssessmentIcon, <AssessmentIcon />],
    주문관리: [AddShoppingCartIcon, <AddShoppingCartIcon />],
    '취소/환불 관리': [ShoppingCartIcon, <ShoppingCartIcon />],
    상품관리: [LocalMallIcon, <LocalMallIcon />],
    '외부채널연동상품 관리': [ShareIcon, <ShareIcon />],
    고객응대관리: [EmojiEmotionsIcon, <EmojiEmotionsIcon />],
    정산관리: [IsoIcon, <IsoIcon />],
    진열관리: [VisibilityIcon, <VisibilityIcon />],
    '기획전/쿠폰관리': [CardGiftcardIcon, <CardGiftcardIcon />],
    푸시: [NotificationsActiveIcon, <NotificationsActiveIcon />],
    회원관리: [PersonIcon, <PersonIcon />],
    기타: [MoreHorizIcon, <MoreHorizIcon />],
    '이전 버전 관리': [SettingsIcon, <SettingsIcon />],
  },
  foldData: [
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
  ],
  sideList: [
    {
      id: '1',
      name: '홈',
      icon: HomeIcon,
      link: '/product/registration',
      list: [],
    },
    {
      id: '2',
      name: '공지사항',
      icon: PersonIcon,
      list: [
        { id: '3', name: '브랜디 공지', link: '/product/registration' },
        { id: '4', name: '기획전 상품 신청', link: '/product/registration' },
      ],
    },
    {
      id: '5',
      name: '통계',
      icon: PersonIcon,
      list: [
        { id: '6', name: '기간별 통계', link: '/product/registration' },
        { id: '7', name: '베스트 상품분석', link: '/product/registration' },
        {
          id: '8',
          name: '판매추세 분석(상품별)',
          link: '/product/registration',
        },
      ],
    },
    {
      id: '9',
      name: '주문관리',
      icon: PersonIcon,
      list: [
        { id: '10', name: '전체주문관리', link: '/product/registration' },
        { id: '11', name: '상품준비관리', link: '/product/registration' },
        { id: '12', name: '배송준비관리', link: '/product/registration' },
        {
          id: '13',
          name: '배송중관리',
          link: '/product/registration',
        },
        { id: '14', name: '배송완료관리', link: '/product/registration' },
        { id: '15', name: '구매확정관리', link: '/product/registration' },
      ],
    },
    {
      id: '16',
      name: '취소/환불 관리',
      icon: PersonIcon,
      list: [
        { id: '17', name: '환불요청관리', link: '/product/registration' },
        { id: '18', name: '반품진행관리', link: '/product/registration' },
        { id: '19', name: '환불승인중관리', link: '/product/registration' },
        {
          id: '20',
          name: '환불완료관리',
          link: '/product/registration',
        },
        { id: '21', name: '주문취소중관리', link: '/product/registration' },
        { id: '22', name: '주문취소완료관리', link: '/product/registration' },
      ],
    },
    {
      id: '23',
      name: '상품관리',
      icon: PersonIcon,
      list: [
        { id: '24', name: '상품관리', link: '/product/registration' },
        { id: '25', name: '상품등록', link: '/product/registration' },
        { id: '26', name: '연동상품관리', link: '/product/registration' },
        {
          id: '27',
          name: '연동상품 카테고리관리',
          link: '/product/registration',
        },
      ],
    },
    {
      id: '28',
      name: '고객응대관리',
      icon: PersonIcon,
      list: [
        { id: '29', name: 'Q&A 관리', link: '/product/registration' },
        { id: '30', name: '텍스트 리뷰', link: '/product/registration' },
        { id: '31', name: '포토 리뷰', link: '/product/registration' },
      ],
    },
    {
      id: '32',
      name: '정산관리',
      icon: PersonIcon,
      list: [
        { id: '33', name: '정산관리', link: '/product/registration' },
        { id: '34', name: '셀러별 정산요약', link: '/product/registration' },
        { id: '35', name: '셀러별 판매수수료', link: '/product/registration' },
        {
          id: '36',
          name: '주문별 판매수수료',
          link: '/product/registration',
        },
      ],
    },
    {
      id: '37',
      name: '진열관리',
      icon: PersonIcon,
      list: [{ id: '38', name: '상점진열관리', link: '/product/registration' }],
    },
    {
      id: '39',
      name: '회원관리',
      icon: ShoppingCartIcon,
      list: [
        { id: '40', name: '셀러 정보 관리', link: '/product/registration' },
        { id: '41', name: '페널티 셀러 관리', link: '/product/registration' },
        { id: '42', name: '도매처 관리', link: '/product/registration' },
      ],
    },
  ],
  menu: [
    {
      id: '1',
      list: [
        {
          id: '2',
          name: '브랜디 공지',
          topmenu: '공지사항',
          topmenu_id: '1',
          url: '/brandi/notice/notice_lists',
        },
        {
          id: '3',
          name: '기획전 상품 신청',
          topmenu: '공지사항',
          topmenu_id: '1',
          url: '/brandi/events/join',
        },
      ],
      name: '',
      topmenu: '공지사항',
      topmenu_id: '1',
      url: 'icon-speech',
    },
    {
      id: '4',
      list: [
        {
          id: '5',
          name: '시간단위분석',
          topmenu: '통계',
          topmenu_id: '4',
          url: '/brandi/statistics/per_time',
        },
        {
          id: '6',
          name: 'KPI_커머스',
          topmenu: '통계',
          topmenu_id: '4',
          url: '/brandi/cstatistics/kpi',
        },
        {
          id: '7',
          name: 'KPI_커뮤니티',
          topmenu: '통계',
          topmenu_id: '4',
          url: '/brandi/statistics/kpi',
        },
        {
          id: '8',
          name: '리텐션',
          topmenu: '통계',
          topmenu_id: '4',
          url: '/brandi/statistics/retention',
        },
        {
          id: '9',
          name: '판매분석(상품)',
          topmenu: '통계',
          topmenu_id: '4',
          url: '/brandi/cstatistics/salesAnalysisProduct',
        },
        {
          id: '10',
          name: '판매분석(셀러)',
          topmenu: '통계',
          topmenu_id: '4',
          url: '/brandi/cstatistics/salesAnalysisSeller',
        },
        {
          id: '11',
          name: '추세분석(상품)',
          topmenu: '통계',
          topmenu_id: '4',
          url: '/brandi/cstatistics/trendAnalysisProduct',
        },
        {
          id: '12',
          name: '추세분석(셀러)',
          topmenu: '통계',
          topmenu_id: '4',
          url: '/brandi/cstatistics/trendAnalysisSeller',
        },
      ],
      name: '',
      topmenu: '통계',
      topmenu_id: '4',
      url: 'icon-bar-chart',
    },
    {
      id: '13',
      list: [
        {
          id: '14',
          name: '전체주문 관리',
          topmenu: '주문관리',
          topmenu_id: '13',
          url: '/brandi/order/masterAllOrderList',
        },
        {
          id: '15',
          name: '결제대기관리',
          topmenu: '주문관리',
          topmenu_id: '13',
          url: '/brandi/order/masterPaymentWatingList',
        },
        {
          id: '16',
          name: '결제완료관리',
          topmenu: '주문관리',
          topmenu_id: '13',
          url: '/brandi/order/masterPaymentCompleteList',
        },
        {
          id: '17',
          name: '상품준비관리',
          topmenu: '주문관리',
          topmenu_id: '13',
          url: '/brandi/order/masterProductPrepareList',
        },
        {
          id: '18',
          name: '배송준비관리',
          topmenu: '주문관리',
          topmenu_id: '13',
          url: '/brandi/order/masterDeliveryPrepareList',
        },
        {
          id: '19',
          name: '배송중관리',
          topmenu: '주문관리',
          topmenu_id: '13',
          url: '/brandi/order/masterDeliveryList',
        },
        {
          id: '20',
          name: '배송완료관리',
          topmenu: '주문관리',
          topmenu_id: '13',
          url: '/brandi/order/masterDeliveryCompleteList',
        },
        {
          id: '21',
          name: '구매확정관리',
          topmenu: '주문관리',
          topmenu_id: '13',
          url: '/brandi/order/masterOrderConfirmList',
        },
      ],
      name: '',
      topmenu: '주문관리',
      topmenu_id: '13',
      url: 'icon-basket-loaded',
    },
    {
      id: '22',
      list: [
        {
          id: '23',
          name: '환불요청관리',
          topmenu: '취소/환불 관리',
          topmenu_id: '22',
          url: '/brandi/refund_order/masterRefundRequestList',
        },
        {
          id: '24',
          name: '반품진행관리',
          topmenu: '취소/환불 관리',
          topmenu_id: '22',
          url: '/brandi/refund_order/masterRefundGoodsList',
        },
        {
          id: '25',
          name: '환불승인중관리',
          topmenu: '취소/환불 관리',
          topmenu_id: '22',
          url: '/brandi/refund_order/masterRefundConfirmList',
        },
        {
          id: '26',
          name: '환불완료관리',
          topmenu: '취소/환불 관리',
          topmenu_id: '22',
          url: '/brandi/refund_order/masterRefundCompleteList',
        },
        {
          id: '27',
          name: '주문취소중관리',
          topmenu: '취소/환불 관리',
          topmenu_id: '22',
          url: '/brandi/refund_order/masterCancelConfirmList',
        },
        {
          id: '28',
          name: '주문취소완료관리',
          topmenu: '취소/환불 관리',
          topmenu_id: '22',
          url: '/brandi/refund_order/masterCancelCompleteList',
        },
        {
          id: '29',
          name: '환불요청관리',
          topmenu: '취소/환불 관리',
          topmenu_id: '22',
          url: '/brandi/refund_order/sellerRefundRequestList',
        },
        {
          id: '30',
          name: '반품진행관리',
          topmenu: '취소/환불 관리',
          topmenu_id: '22',
          url: '/brandi/refund_order/sellerRefundGoodsList',
        },
        {
          id: '31',
          name: '환불승인중관리',
          topmenu: '취소/환불 관리',
          topmenu_id: '22',
          url: '/brandi/refund_order/sellerRefundConfirmList',
        },
        {
          id: '32',
          name: '환불완료관리',
          topmenu: '취소/환불 관리',
          topmenu_id: '22',
          url: '/brandi/refund_order/sellerRefundCompleteList',
        },
        {
          id: '33',
          name: '주문취소중관리',
          topmenu: '취소/환불 관리',
          topmenu_id: '22',
          url: '/brandi/refund_order/sellerCancelConfirmList',
        },
        {
          id: '34',
          name: '주문취소완료관리',
          topmenu: '취소/환불 관리',
          topmenu_id: '22',
          url: '/brandi/refund_order/sellerCancelCompleteList',
        },
      ],
      name: '',
      topmenu: '취소/환불 관리',
      topmenu_id: '22',
      url: 'icon-basket',
    },
    {
      id: '35',
      list: [
        {
          id: '36',
          name: '상품 관리',
          topmenu: '상품관리',
          topmenu_id: '35',
          url: '/brandi/cproduct',
        },
        {
          id: '37',
          name: '상품 등록',
          topmenu: '상품관리',
          topmenu_id: '35',
          url: '/brandi/cproduct/productRegistPage',
        },
        {
          id: '38',
          name: '럭키투데이 관리',
          topmenu: '상품관리',
          topmenu_id: '35',
          url: '/brandi/cproduct/luckyTodayList',
        },
        {
          id: '39',
          name: '연동상품관리',
          topmenu: '상품관리',
          topmenu_id: '35',
          url: '/connecti/product',
        },
        {
          id: '40',
          name: '연동상품 카테고리관리',
          topmenu: '상품관리',
          topmenu_id: '35',
          url: '/connecti/category',
        },
      ],
      name: '',
      topmenu: '상품관리',
      topmenu_id: '35',
      url: 'icon-handbag',
    },
    {
      id: '41',
      list: [
        {
          id: '42',
          name: '연동상품관리',
          topmenu: '외부채널연동상품 관리',
          topmenu_id: '41',
          url: '/connecti/external',
        },
        {
          id: '43',
          name: '수동연동관리',
          topmenu: '외부채널연동상품 관리',
          topmenu_id: '41',
          url: '/connecti/external/manual',
        },
      ],
      name: '',
      topmenu: '외부채널연동상품 관리',
      topmenu_id: '41',
      url: 'icon-share',
    },
    {
      id: '44',
      list: [
        {
          id: '45',
          name: 'CRM 관리 (고객)',
          topmenu: '고객응대관리',
          topmenu_id: '44',
          url: '/brandi/crm/customer',
        },
        {
          id: '46',
          name: 'CRM 관리 (셀러)',
          topmenu: '고객응대관리',
          topmenu_id: '44',
          url: '/brandi/crm/seller',
        },
        {
          id: '47',
          name: 'Q&A 관리',
          topmenu: '고객응대관리',
          topmenu_id: '44',
          url: '/brandi/inquiry/inquiry_list',
        },
        {
          id: '48',
          name: '텍스트 리뷰',
          topmenu: '고객응대관리',
          topmenu_id: '44',
          url: '/brandi/review/textReviewList',
        },
        {
          id: '49',
          name: '포토 리뷰',
          topmenu: '고객응대관리',
          topmenu_id: '44',
          url: '/brandi/review/photoReviewList',
        },
        {
          id: '50',
          name: '인증번호 관리',
          topmenu: '고객응대관리',
          topmenu_id: '44',
          url: '/brandi/certificationCode/certificationCodeDetail',
        },
      ],
      name: '',
      topmenu: '고객응대관리',
      topmenu_id: '44',
      url: 'icon-emoticon-smile',
    },
    {
      id: '68',
      list: [
        {
          id: '69',
          name: '(iOS) 홈 - 홈 탭 진열관리',
          topmenu: '진열관리',
          topmenu_id: '68',
          url: '/brandi/exhibition/homeTabExhibition/iOS',
        },
        {
          id: '70',
          name: '(AOS) 홈 - 홈 탭 진열관리',
          topmenu: '진열관리',
          topmenu_id: '68',
          url: '/brandi/exhibition/homeTabExhibition/AOS',
        },
        {
          id: '71',
          name: '홈 - 베스트 탭 진열관리',
          topmenu: '진열관리',
          topmenu_id: '68',
          url: '/brandi/exhibition/bestTabExhibition',
        },
        {
          id: '72',
          name: '(iOS) 홈 - 쇼핑몰·마켓 탭 진열관리',
          topmenu: '진열관리',
          topmenu_id: '68',
          url: '/brandi/exhibition/trendTabExhibition/iOS',
        },
        {
          id: '73',
          name: '(AOS) 홈 - 쇼핑몰·마켓 탭 진열관리',
          topmenu: '진열관리',
          topmenu_id: '68',
          url: '/brandi/exhibition/trendTabExhibition/AOS',
        },
        {
          id: '74',
          name: '홈 - 브랜드 탭 진열관리',
          topmenu: '진열관리',
          topmenu_id: '68',
          url: '/brandi/exhibition/brandTabExhibition',
        },
        {
          id: 75,
          name: '홈 - 뷰티 탭 진열관리',
          topmenu: '진열관리',
          topmenu_id: '68',
          url: '/brandi/exhibition/beautyTabExhibition',
        },
        {
          id: 76,
          name: '홈 - 특가 탭 진열관리',
          topmenu: '진열관리',
          topmenu_id: '68',
          url: '/brandi/cproduct/spclpc',
        },
        {
          id: 77,
          name: '카테고리 진열관리',
          topmenu: '진열관리',
          topmenu_id: '68',
          url: '/brandi/exhibition/categoryExhibition',
        },
        {
          id: 78,
          name: '스토어 진열 관리',
          topmenu: '진열관리',
          topmenu_id: '68',
          url: '/brandi/seller/market_exhbi_mngr',
        },
        {
          id: 79,
          name: '스플래시 이미지 관리',
          topmenu: '진열관리',
          topmenu_id: '68',
          url: '/brandi/image_control',
        },
        {
          id: 80,
          name: '스토어 상세 진열 관리',
          topmenu: '진열관리',
          topmenu_id: '68',
          url: '/brandi/seller/market_detail_exhbi_mngr',
        },
        {
          id: 81,
          name: '배너 관리',
          topmenu: '진열관리',
          topmenu_id: '68',
          url: '/brandi/design/commerceBannerControl',
        },
      ],
      name: '',
      topmenu: '진열관리',
      topmenu_id: '68',
      url: 'icon-eye',
    },
    {
      id: '82',
      list: [
        {
          id: 83,
          name: '기획전 관리',
          topmenu: '기획전/쿠폰관리',
          topmenu_id: '82',
          url: '/brandi/events',
        },
        {
          id: 84,
          name: '기획전 댓글 관리',
          topmenu: '기획전/쿠폰관리',
          topmenu_id: '82',
          url: '/brandi/events/event_answer_list',
        },
        {
          id: 85,
          name: '포인트 관리',
          topmenu: '기획전/쿠폰관리',
          topmenu_id: '82',
          url: '/brandi/coupon/coupon_list',
        },
        {
          id: 86,
          name: '쿠폰 관리',
          topmenu: '기획전/쿠폰관리',
          topmenu_id: '82',
          url: '/brandi/coupon/prduct_coupon_list',
        },
        {
          id: 87,
          name: '포인트 일괄 지급',
          topmenu: '기획전/쿠폰관리',
          topmenu_id: '82',
          url: '/brandi/coupon/pointProcess',
        },
      ],
      name: '',
      topmenu: '기획전/쿠폰관리',
      topmenu_id: '82',
      url: 'icon-present',
    },
    {
      id: '88',
      list: [
        {
          id: 89,
          name: '푸시 발송',
          topmenu: '푸시',
          topmenu_id: '88',
          url: '/brandi/push',
        },
        {
          id: 90,
          name: '푸시 메시지 목록',
          topmenu: '푸시',
          topmenu_id: '88',
          url: '/brandi/push/message',
        },
      ],
      name: '',
      topmenu: '푸시',
      topmenu_id: '88',
      url: 'icon-bell',
    },
    {
      id: '91',
      list: [
        {
          id: 92,
          name: '회원 관리_커뮤니티',
          topmenu: '회원관리',
          topmenu_id: '91',
          url: '/brandi/member',
        },
        {
          id: 93,
          name: '회원 관리_커머스',
          topmenu: '회원관리',
          topmenu_id: '91',
          url: '/brandi/member/commerce_member',
        },
        {
          id: 94,
          name: '회원 그룹 관리',
          topmenu: '회원관리',
          topmenu_id: '91',
          url: '/brandi/member/group',
        },
        {
          id: 95,
          name: '셀러 정보 관리',
          topmenu: '회원관리',
          topmenu_id: '91',
          url: '/brandi/seller/seller_my_page',
        },
        {
          id: 96,
          name: '페널티 셀러 관리',
          topmenu: '회원관리',
          topmenu_id: '91',
          url: '/brandi/sellerPenalty/penaltyList',
        },
        {
          id: 97,
          name: '회원 탈퇴 관리',
          topmenu: '회원관리',
          topmenu_id: '91',
          url: '/brandi/member/delete',
        },
        {
          id: 98,
          name: '셀러 계정 관리',
          topmenu: '회원관리',
          topmenu_id: '91',
          url: '/brandi/account',
        },
        {
          id: 99,
          name: '도매처 관리',
          topmenu: '회원관리',
          topmenu_id: '91',
          url: '/brandi/wholesale',
        },
      ],
      name: '',
      topmenu: '회원관리',
      topmenu_id: '91',
      url: 'icon-user',
    },
    {
      id: '100',
      list: [
        {
          id: 101,
          name: '단축 URL 공유',
          topmenu: '기타',
          topmenu_id: '100',
          url: '/brandi/shorten',
        },
        {
          id: 102,
          name: '서비스 로그 목록',
          topmenu: '기타',
          topmenu_id: '100',
          url: '/brandi/service_log',
        },
        {
          id: 103,
          name: '공휴일 관리',
          topmenu: '기타',
          topmenu_id: '100',
          url: '/brandi/holiday',
        },
        {
          id: 104,
          name: '메뉴 권한 관리',
          topmenu: '기타',
          topmenu_id: '100',
          url: '/brandi/authorGroup',
        },
        {
          id: 105,
          name: '브랜디 계정 관리',
          topmenu: '기타',
          topmenu_id: '100',
          url: '/brandi/masterAccount',
        },
        {
          id: 106,
          name: '관리 도구',
          topmenu: '기타',
          topmenu_id: '100',
          url: '/brandi/manageTool',
        },
      ],
      name: '',
      topmenu: '기타',
      topmenu_id: '100',
      url: 'icon-equalizer',
    },
    {
      id: '107',
      list: [
        {
          id: 108,
          name: '스토리관리',
          topmenu: '이전 버전 관리',
          topmenu_id: '107',
          url: '/brandi/story',
        },
        {
          id: 109,
          name: '브랜드 관리',
          topmenu: '이전 버전 관리',
          topmenu_id: '107',
          url: '/brandi/brand',
        },
        {
          id: 110,
          name: '브랜드 신청 관리',
          topmenu: '이전 버전 관리',
          topmenu_id: '107',
          url: '/brandi/brand_recommend',
        },
        {
          id: 111,
          name: '아이템 관리',
          topmenu: '이전 버전 관리',
          topmenu_id: '107',
          url: '/brandi/media',
        },
        {
          id: 112,
          name: '신고 아이템 관리',
          topmenu: '이전 버전 관리',
          topmenu_id: '107',
          url: '/brandi/media/statement_list',
        },
        {
          id: '113',
          name: '댓글 관리',
          topmenu: '이전 버전 관리',
          topmenu_id: '107',
          url: '/brandi/media/answer',
        },
        {
          id: 114,
          name: '접속',
          topmenu: '이전 버전 관리',
          topmenu_id: '107',
          url: '/brandi/statistics/access',
        },
        {
          id: 115,
          name: '카테고리 관리',
          topmenu: '이전 버전 관리',
          topmenu_id: '107',
          url: '/brandi/category',
        },
      ],
      name: '',
      topmenu: '이전 버전 관리',
      topmenu_id: '107',
      url: 'icon-settings',
    },
  ],
};

export default data;
